### ISSUE TITLE
Создан  свой BOOLEAN в СУБД

### ISSUE THREAD

**Issue by undestroyer** [prosvetovEvgeniy/eshopper#1]
[m170728_102707_create_product_table.php#L24](https://github.com/prosvetovEvgeniy/eshopper/blob/master/migrations/m170728_102707_create_product_table.php#L24)
[m170728_103357_create_order_table.php#L21](https://github.com/prosvetovEvgeniy/eshopper/blob/master/migrations/m170728_103357_create_order_table.php#L21)
`'new' => "ENUM('0', '1') NOT NULL DEFAULT '0'",`

Придумал свой BOOLEAN, он уже есть во всех СУБД
[MySQL Manual](https://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html)

Если сможешь сконвертировать свой ENUM в BOOLEAN без потери данных - будет круто.

**Comment by prosvetovEvgeniy** [comment]
c7e86f703b43945ecce2f21d034c7ba48308c7ad

**Comment by undestroyer** [comment]
Не стоит исправлять код старых миграций. Если у меня создана база из старого набора миграций, то исправление старой миграции не исправит мою базу и моя база больше не соответствует коду

**Comment by prosvetovEvgeniy** [comment]
Исправил 8d597a317c76cdc0122f3563eaa69545be50eba7
