### ISSUE TITLE
Избыточный код

### ISSUE THREAD

**Issue by undestroyer** [prosvetovEvgeniy/eshopper#10]
Берем дату, получаем порядковый номер месяца через `$date->format('n')`
Получаем название месяца по его порядковому номеру используя `getMonthName($number)`
Получаем номер месяца по его названию используя `getMonthIndex($name)`

Номер месяца уже получен в `$date->format('n')`

https://github.com/prosvetovEvgeniy/eshopper/blob/75d238afe9ff4db626a7cb36665d8b1196e030f1/modules/admin/controllers/SalaryController.php#L120

**Comment by prosvetovEvgeniy** [comment]
e4393d7f5058af2f1fe70cb8c92747a3c6685135
