### ISSUE TITLE
Снять требование загрузки картинки

### ISSUE THREAD

**Issue by undestroyer** [prosvetovEvgeniy/eshopper#2]
Требовать картинку очень жестоко. Стоит разрешить оставлять картинку пустой, а если ее нет - ставить заглушку.

[m170728_102707_create_product_table.php#L23](https://github.com/prosvetovEvgeniy/eshopper/blob/master/migrations/m170728_102707_create_product_table.php#L23)

`'img' => $this->string()->notNull(),`

**Comment by prosvetovEvgeniy** [comment]
85839a671e1c52ca86a31f0e3ad3071ec82b3353 - Я вообще удалил это поле из таблицы product, т.к для работы с картинками я использую "yii2images" модуль https://github.com/prosvetovEvgeniy/eshopper/blob/master/config/web.php

**Comment by prosvetovEvgeniy** [comment]
85839a671e1c52ca86a31f0e3ad3071ec82b3353 - Я вообще удалил это поле из таблицы product, т.к для работы с картинками я использую "yii2images" модуль.

**Comment by undestroyer** [comment]
Тоже что и в #1 Править миграцию можно пока ее нигде не накатывали кроме твоего локального сервера. Стоит вернуть исправленные миграции в предыдущее состояние и написать новые

**Comment by prosvetovEvgeniy** [comment]
Исправил 0da4c06adfe9891efad82f622d8d86dbd51c3f11
