### ISSUE TITLE
Вычисляемое поле хранится в СУБД

### ISSUE THREAD

**Issue by undestroyer** [prosvetovEvgeniy/eshopper#3]
```php
$this->createTable('order_items', [
            'id' => $this->primaryKey(),
            'order_id' => $this->integer()->notNull(),
            'product_id' => $this->integer()->notNull(),
            'name' => $this->string()->notNull(),
            'price' => $this->float()->notNull(),
            'qty_item' => $this->integer()->notNull(),
            'sum_item' => $this->integer()->notNull(),
        ]);
```

[m170728_103431_create_order_items_table.php#L22](https://github.com/prosvetovEvgeniy/eshopper/blob/master/migrations/m170728_103431_create_order_items_table.php#L22)

Каждый `order_item` хранит в себе:
* цену
* количество
* стоимость = количество * цена

Вычисляемое поле `sum_item` не стоит хранить в базе, лучше сделать метод, который будет возвращать это значение

```php
public function getSumItem() {
    return $this->price*$this->qty_item;
}

// благодаря переопределенным магическим методам, 
// стоимость можно получать как $model->sumItem;
```

**Comment by prosvetovEvgeniy** [comment]
2502c39090002bb0b1c2182451e4ba819a63a89a

**Comment by prosvetovEvgeniy** [comment]
dc4d934532bec61d5157a11944a3abf3b5aa638e

**Comment by prosvetovEvgeniy** [comment]
Версия с добавленной миграцией для удаления поля a2a7cee714874d29376226f294f18c88dffd7552
