### ISSUE TITLE
Избыточные данные в таблице order

### ISSUE THREAD

**Issue by undestroyer** [prosvetovEvgeniy/eshopper#4]
[m170728_103357_create_order_table.php#L21](https://github.com/prosvetovEvgeniy/eshopper/blob/master/migrations/m170728_103357_create_order_table.php#L21)

```php 
'qty' => $this->integer(10)->notNull(),
'sum' => $this->float()->notNull(),
```

`qty` - количество товаров в заказе? Оно вычисляемое, можно забрать через обращение к товарам в заказе.
`sum` - общая сумма в заказе? Также вычисляемо через товары

**Comment by prosvetovEvgeniy** [comment]
4155100eefb5403f714fb08d66e4fe4e474cd4db

**Comment by prosvetovEvgeniy** [comment]
https://github.com/prosvetovEvgeniy/eshopper/commit/d4e2bdd17a2efa7867f7693aefe487baaa239959
