### ISSUE TITLE
Клиентов выделить в отдельную таблицу

### ISSUE THREAD

**Issue by undestroyer** [prosvetovEvgeniy/eshopper#5]
```php
'name' => $this->string()->notNull(),
 'email' => $this->string()->notNull(),
'phone' => $this->string()->notNull(),
'address' => $this->string()->notNull()
```
[m170728_103357_create_order_table.php#L22](https://github.com/prosvetovEvgeniy/eshopper/blob/master/migrations/m170728_103357_create_order_table.php#L22)

Данные о клиентах нужно выделить. В любом ИМ (интернет-магазине) по каждому клиенту строится история покупок для аналитики и маркетинга. 

Выделить без потери данных и с защитой от дубляжа клиентов (если за время работы старой архитектуры один клиент сделал несколько заказов, при выделении оба заказа должны попасть на его аккаунт).

**Comment by prosvetovEvgeniy** [comment]
d4e2bdd17a2efa7867f7693aefe487baaa239959
