### ISSUE TITLE
Удаление товара из СУБД может вызвать сбои

### ISSUE THREAD

**Issue by undestroyer** [prosvetovEvgeniy/eshopper#6]
[ProductController.php#L126](https://github.com/prosvetovEvgeniy/eshopper/blob/master/modules/admin/controllers/ProductController.php#L126)

```php
public function actionDelete($id)
    {
        //удаляем фотографии товара
        Image::deleteAll("itemId = {$id}");
        $this->findModel($id)->delete();
        return $this->redirect(['index']);
    }
```

После удаления товара, данные из связанных таблиц (`order_item`) останутся, но будут невалидны. Старые заказы с удаленным товарам начнут давать сбои.

Предлагаю никогда не удалять товар, а добавить специальный флаг `deleted BOOLEAN`, который будет показывать что товар удален.

**Comment by prosvetovEvgeniy** [comment]
56c225178284245bfc22468fd06ff063d336fbe0

**Comment by prosvetovEvgeniy** [comment]
56c225178284245bfc22468fd06ff063d336fbe0
