### ISSUE TITLE
Убрать лишнее из сессии

### ISSUE THREAD

**Issue by undestroyer** [prosvetovEvgeniy/eshopper#7]
Сессии - ненадежное хранилище. Может потерять данные.
Предлагаю к корзинам в СУБД добавить уникальную строку (например UUID). Добавлять ее в cookie.
Если у зашедшего пользователя нет cookie с идентификатором корзины - создавать новую.
У 1 пользователя может быть только 1 корзина, чтобы при входе с разных устройств у него была одна и та же корзина.

**Comment by prosvetovEvgeniy** [comment]
https://github.com/prosvetovEvgeniy/eshopper/commits/cart_branch
