### ISSUE TITLE
Статичные файлы контента должны быть проигнорированы Git'ом

### ISSUE THREAD

**Issue by undestroyer** [prosvetovEvgeniy/eshopper#8]
Директория [web/upload](https://github.com/prosvetovEvgeniy/eshopper/tree/master/web/upload) содержит в себе файлы контента (картинки которые принадлежат конкретному магазину). В исходниках не должно быть такого содержимого. 

Нужно убрать в .gitignore

**Comment by prosvetovEvgeniy** [comment]
dc4d934532bec61d5157a11944a3abf3b5aa638e
