### ISSUE TITLE
PhpDoc

### ISSUE THREAD

**Issue by undestroyer** [prosvetovEvgeniy/eshopper#9]
Код крайне желательно документировать. Для документации есть специальный формат PhpDoc

Как говорил один мой знакомый: Писать нужно с мыслью о том что после тебя этот код будет читать психопат с шизой и бензопилой у которого есть твой домашний адрес

https://github.com/prosvetovEvgeniy/eshopper/blob/75d238afe9ff4db626a7cb36665d8b1196e030f1/modules/admin/controllers/SalaryController.php#L63

**Comment by prosvetovEvgeniy** [comment]
e4393d7f5058af2f1fe70cb8c92747a3c6685135
